### ISSUE TITLE
Breaks on large Slack team

### ISSUE THREAD

**Issue by bootstraponline** [hfaran/slack-auto-export#1]
```python
SlackAutoExport: Retrieved 0 messages
Traceback (most recent call last):
  File "./slack_auto_export.py", line 110, in <module>
    main()
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./slack_auto_export.py", line 106, in main
    s.write_history(output_dir)
  File "./slack_auto_export.py", line 75, in write_history
    for channel_name, data in self.history.items():
  File "./slack_auto_export.py", line 57, in history
    self._history = self._get_history()
  File "./slack_auto_export.py", line 47, in _get_history
    history[channel_name] = self._get_channel_history(channel_id)
  File "./slack_auto_export.py", line 37, in _get_channel_history
    latest = m.body['messages'][-1]['ts']
IndexError: list index out of range
```

**Comment by hfaran** [comment]
Just pushed [this](https://github.com/hfaran/slack-auto-export/commit/0268b0c124b1fe1d0194f4ec063db7fe51f37e83), which might fix it. Try and see what happens.

**Comment by bootstraponline** [comment]
Works. The export is incompatible with slack-export-viewer. I'll open a new issue for that.
